AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Deploying Resources for ALS
Resources:
  ALSLambdaExecutionRole:
    Properties:
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess
      AssumeRolePolicyDocument:
        Statement:
        - Action:
          - sts:AssumeRole
          Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
        Version: 2012-10-17
      Policies:
      - PolicyName: lambdaRoleAPIG
        PolicyDocument:
          Statement:
          - Action:
            - cloudwatch:*
            - logs:*
            Effect: Allow
            Resource: '*'
          Version: 2012-10-17
    Type: AWS::IAM::Role
  ALSPredict:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://als-sam-bucket/67cf9a9b425e1712572732446c4081b6
      Handler: predict.lambda_handler
      Runtime: python3.7
      Role:
        Fn::GetAtt:
        - ALSLambdaExecutionRole
        - Arn
      Timeout: 30
      MemorySize: 256
